//
// Created by emily on 29.05.22.
//

#ifndef QMK_FIRMWARE_EMILY3403_CONFIG_H
#define QMK_FIRMWARE_EMILY3403_CONFIG_H

#define MK_KINETIC_SPEED

#define MOUSEKEY_INTERVAL 10
#define MOUSEKEY_MOVE_DELTA 5
#define MOUSEKEY_MAX_SPEED 10
#define MOUSEKEY_INITIAL_SPEED 80
#define MOUSEKEY_BASE_SPEED 1000
#define MOUSEKEY_TIME_TO_MAX 20

#define MOUSEKEY_WHEEL_INTERVAL 255
#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 1
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 1
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 1

// Disable scrolling acceleration
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0

#define UNICODE_SELECTED_MODES UC_LNX



#endif // QMK_FIRMWARE_EMILY3403_CONFIG_H
