
#ifndef QMK_FIRMWARE_EMILY3403_CONFIG_H
#define QMK_FIRMWARE_EMILY3403_CONFIG_H

#define MOUSEKEY_DELAY 0
#define MOUSEKEY_INTERVAL 10
#define MOUSEKEY_MOVE_DELTA 5
#define MOUSEKEY_MAX_SPEED 10
#define MOUSEKEY_INITIAL_SPEED 80
#define MOUSEKEY_BASE_SPEED 1000
#define MOUSEKEY_TIME_TO_MAX 20

#define MOUSEKEY_WHEEL_INTERVAL 255
#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 16
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 32
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 48
#define MOUSEKEY_WHEEL_MAX_SPEED 3

// Disable scrolling acceleration
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0

#define UNICODE_SELECTED_MODES UC_LNX



#endif // QMK_FIRMWARE_EMILY3403_CONFIG_H
